name: persona_expense_tracker
description: A Persona 5 themed expense tracker app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.3
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  intl: ^0.19.0
  fl_chart: ^0.66.1
  pdf: ^3.10.7
  printing: ^5.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logobgb.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/logobgb.png"
  web:
    generate: true
    image_path: "assets/images/logobgb.png"
    background_color: "#000000"
    theme_color: "#E53935"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: lib/fonts/Roboto-Regular.ttf
        - asset: lib/fonts/Roboto-Bold.ttf
          weight: 700
